RAW_FOLDER="/Users/lscpuser/Documents/ALSE/pilot5/train"

ffmpeg -i $RAW_FOLDER/Dogflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/Dogflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/Dogflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/Dogjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/Dogjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/Dogwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/Dogwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/Dogwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/Dogwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/Dogwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/Dogwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun0_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/2sheepflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2sheepflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/2sheepjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2sheepjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/2sheepwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2sheepwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2sheepwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1_2.mov
ffmpeg -i $RAW_FOLDER/2sheepwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2sheepwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0_2.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0_2.mov
ffmpeg -i $RAW_FOLDER/2sheepwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun1_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2catflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb0_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2catjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb1_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/2catwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb2_ProgressiveN_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/2catwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Pluralnoun_verb2_ProgressiveY_Pluralverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/catflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/catflip.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb0_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catjumping.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb1_ProgressiveY_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/catwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catwalk.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveN_Singularverb_Disrupter1.mov
ffmpeg -i $RAW_FOLDER/catwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter1_noun2_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter0.mov
ffmpeg -i $RAW_FOLDER/catwalking.mp4  -itsoffset 00:00:02.0 -i $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter1.aiff -map 0:0 -map 1:0 -c:v copy -c:a copy $RAW_FOLDER/A_Disrupter0_noun2_Singularnoun_verb2_ProgressiveY_Singularverb_Disrupter1.mov















